package co.istad.elearningcodejourney.feature.course;

import co.istad.elearningcodejourney.feature.category.Category;
import co.istad.elearningcodejourney.feature.category.CategoryRepository;
import co.istad.elearningcodejourney.feature.course.dto.CourseResponse;
import co.istad.elearningcodejourney.feature.course.dto.CreateCourseRequest;
import co.istad.elearningcodejourney.feature.course.dto.UpdateCourseRequest;
import co.istad.elearningcodejourney.feature.instructor.InstructorProfile;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.http.HttpStatus;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.time.LocalDateTime;

@Service
@Slf4j
@RequiredArgsConstructor
public class CourseServiceImpl implements CourseService{

    private final CourseRepository courseRepository;
    private final CategoryRepository categoryRepository;
    private final CourseMapper courseMapper;

    @Override
    public CourseResponse createCourse(CreateCourseRequest createCourseRequest, Jwt jwt) {

        // validate slug
        if (courseRepository.existsBySlug(createCourseRequest.slug())) {
            throw new ResponseStatusException(
                    HttpStatus.CONFLICT,
                    "slug has already been used"
            );
        }

        // validate category
        Category category = categoryRepository.findById(createCourseRequest.categoryId())
                .orElseThrow(() -> new ResponseStatusException(
                        HttpStatus.NOT_FOUND,
                        "Category has not been found"
                ));

        Course course = courseMapper.mapCreateCourseRequestToCourse(createCourseRequest);

        // System data (generated by system)
        course.setCategory(category);
        course.setCountRating(0);
        course.setStarRating(0F);
        course.setIsDeleted(false);
        course.setIsPublished(false);
//        course.setCreatedAt(LocalDateTime.now());
//        course.setUpdatedAt(LocalDateTime.now());
        course.setInstructorProfile(new InstructorProfile(jwt.getSubject()));

        course = courseRepository.save(course);

        return courseMapper.mapCourseToCourseResponse(course);
    }

    @Override
    public Page<CourseResponse> getAllCourses(int page, int size) {
        PageRequest pageRequest = PageRequest.of(page,size);
        return courseRepository.findAllByIsDeletedFalse(pageRequest).map(courseMapper::mapCourseToCourseResponse);
    }

    @Override
    public CourseResponse getCourseBySlug(String slug) {
        Course course = courseRepository.findBySlugAndIsDeletedFalse(slug)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Course not found"));
        return courseMapper.mapCourseToCourseResponse(course);
    }

    @Override
    public CourseResponse updateCourse(String slug, UpdateCourseRequest request) {
        Course course = courseRepository.findBySlugAndIsDeletedFalse(slug)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Course not found"));

        // Update category if provided
        if (request.categoryId() != null) {
            Category category = categoryRepository.findById(request.categoryId())
                    .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Category not found"));
            course.setCategory(category);
        }

        courseMapper.updateCourseFromRequest(request, course);
//        course.setUpdatedAt(LocalDateTime.now());

        return courseMapper.mapCourseToCourseResponse(courseRepository.save(course));
    }

    @Override
    public void deleteCourse(String slug) {
        Course course = courseRepository.findBySlugAndIsDeletedFalse(slug)
                .orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Course not found"));
        course.setIsDeleted(true);
//        course.setUpdatedAt(LocalDateTime.now());
        courseRepository.save(course);
    }

    @Override
    public CourseResponse togglePublish(String slug) {

        Course course = courseRepository.findBySlugAndIsDeletedFalse(slug)
                .orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Course not found"));
        course.setIsPublished(!course.getIsPublished());
//        course.setUpdatedAt(LocalDateTime.now());

        return courseMapper.mapCourseToCourseResponse(courseRepository.save(course));
    }
}
